# Setup
title:               'Today I Learned'
tagline:             'Notes to self about software development'
description:         ''
url:                 '"https://sgnlcntxt.github.io"'
baseurl:             'blog/'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Dustin Dieckmann
  url:               
  email:             ddieckma@chicagobooth.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-146052-15
